### ISSUE TITLE
react native with API [Unhandled promise rejection: TypeError: Network request failed] 

### ISSUE THREAD

**Issue by ALbaron-Awad** [ALbaron-Awad/api_testing#1]
I am trying to connect **(Laravel API) with (React native app),** I test the API in the **postman** and it **working fine**, but when I fetch the API in the react native app I got the following error !

`[Unhandled promise rejection: TypeError: Network request failed]
- node_modules\whatwg-fetch\dist\fetch.umd.js:527:17 in setTimeout$argument_0- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:135:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:387:16 in callTimers
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:425:19 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:112:6 in 
__guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:373:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:4 in 
callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
`
**And in the app, it shows like this:**
![Screenshot_1597963373](https://user-images.githubusercontent.com/51613579/90974346-0cdb1a80-e533-11ea-918b-d3ba75391469.png)

**This is my app.js code(only the fetch function)**:
`
myfun = async()=>{
    
    await fetch('http://localhost:8000/api/login',{
        method:'POST',
        headers:{
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({"email": email, "password": passowrd })
    }).then(res => res.json())
    .then(resData =>{
        alert(resData.message);
    });
  }
`

all the code available in my account!

**Comment by ALbaron-Awad** [comment]
Solved by troubleshooting the localhost

**Comment by ALbaron-Awad** [comment]
Solved by troubleshooting the localhost

**Comment by franmassello** [comment]
Hi @ALbaron-Awad, could you please tell me how you solved this problem? Thanks in advance

**Comment by abdulriiyaz** [comment]
@ALbaron-Awad can you please elaborate more on this
